import { defineCopy } from "@/lib/i18n";

/**
 * El texto de «Sobre mí», en los dos idiomas.
 *
 * Vive fuera del componente porque es contenido —la voz de Jonás—, no texto de
 * interfaz, y porque junto al marcado ocupaba más que el propio marcado. Cada
 * foto lleva su título y su pie para el visor (`data-title`, `data-caption`),
 * el nombre accesible del botón que la amplía y su texto alternativo.
 */
export type AboutPhoto = {
  title: string;
  caption: string;
  label: string;
  alt: string;
};

type Node = { title: string; lead: string; alt: string };

export const ABOUT_COPY = defineCopy({
  es: {
    heroEyebrow: "01 / SOBRE MÍ",
    heroHidden: "Sobre mí. ",
    heroTitle: "Mi pequeño universo.",
    heroNote: ["Misma persona,", "distintos cielos."],
    constellation: "Explora las seis constelaciones",
    portraitAlt: "Jonás sonriendo, con abrigo y luces al fondo",
    place: "BONAO · REPÚBLICA DOMINICANA",
    nodes: {
      roots: { title: "Mis raíces", lead: "Donde empezó todo.", alt: "Río rodeado de vegetación en Bonao" },
      people: { title: "Mi gente", lead: "Las personas que hacen hogar.", alt: "Jonás con su familia en una asamblea internacional" },
      self: { title: "Cómo soy", lead: "Todavía aprendiendo.", alt: "Jonás junto al mar" },
      enjoy: { title: "Lo que disfruto", lead: "Curiosidad, naturaleza y buenas historias.", alt: "Una gran cascada entre vegetación" },
      path: { title: "Mi camino", lead: "Servir, aprender y compartir.", alt: "Un momento compartido durante el voluntariado de mantenimiento" },
      dream: { title: "Lo que sueño", lead: "Una vida sencilla. Mucho por descubrir.", alt: "Una persona contemplando un lago entre montañas" },
    } satisfies Record<string, Node>,
    invitation: "Elige una constelación",
    journeyNav: "Tu lugar en la historia",
    backToMap: "Volver a la constelación",

    rootsEyebrow: "01 / EL PUNTO DE PARTIDA",
    rootsTitle: "Mis raíces.",
    rootsPlace: "Bonao · República Dominicana",
    rootsCoordinates: "18°56′ N · 70°25′ O",
    rootsWords: "Crecí entre ríos y montañas.",
    rootsStory:
      "Bonao es mi punto de partida. Crecer rodeado de montañas, ríos y tanto verde dejó algo en mí: todavía busco esos lugares cuando quiero desconectarme, pensar o simplemente mirar. De ahí viene buena parte de mi gusto por explorar.",
    rootsPhoto: {
      title: "Mis raíces",
      caption: "Entre ríos y montañas, con mis amigos.",
      label: "Ampliar fotografía de la cascada con mis amigos",
      alt: "Jonás con sus amigos frente a una cascada rodeada de vegetación",
    },
    rootsNext: "Y LAS PERSONAS QUE ME ACOMPAÑAN",

    peopleEyebrow: "02 / MIS VÍNCULOS",
    peopleTitle: "Mi gente.",
    peopleLead: "Mi familia es mi primer hogar.",
    peopleSub: "La alegría de mi madre, el esfuerzo de mi padre y la amistad de mi hermana.",
    familyPhoto: {
      title: "Mi familia",
      caption: "Juntos en una asamblea internacional.",
      label: "Ampliar fotografía de mi familia",
      alt: "Jonás y su familia en el auditorio de una asamblea internacional",
    },
    childhoodPhoto: {
      title: "Desde pequeños",
      caption: "Aquí hablábamos de nuestras metas, entre ellas ir a Betel.",
      label: "Ampliar recuerdo de infancia con mi mejor amigo",
      alt: "Jonás y su mejor amigo de niños, frente a unas filas de asientos",
    },
    bethelPhoto: {
      title: "Un sueño compartido",
      caption: "Con mi mejor amigo durante nuestra etapa en Betel.",
      label: "Ampliar fotografía de los dos amigos en Betel",
      alt: "Jonás y su mejor amigo en Betel",
    },
    friendsLine: "Mi mejor amigo y yo, cumpliendo metas y sueños juntos.",
    grandparentsPhoto: {
      title: "Mis abuelos",
      caption: "Lo que aprendí a su lado.",
      label: "Ampliar fotografía de mis abuelos maternos",
      alt: "Los abuelos maternos de Jonás juntos en una mesa",
    },
    grandparentsEyebrow: "MIS ABUELOS",
    grandparentsLine: "Cariño, sabiduría y muchos recuerdos.",
    chosenEyebrow: "AMIGOS, CASI FAMILIA",
    chosenTitle: "También hacen hogar.",
    friendsPhoto: {
      title: "Amigos, casi familia",
      caption: "Amigos que se sienten como familia.",
      label: "Ampliar fotografía: Amigos, casi familia",
      alt: "Amigos compartiendo un rato al aire libre, entre árboles y sillas de jardín",
    },
    callsPhoto: {
      title: "Recuerdos compartidos",
      caption: "Cerca, también a través de una pantalla.",
      label: "Ampliar fotografía: Recuerdos compartidos",
      alt: "Collage de videollamadas con amigos, con un marco de hojas y mensajes",
    },
    peopleNext: "UN POCO MÁS DE MÍ",

    selfPhoto: {
      title: "Junto al mar",
      caption: "Un momento al aire libre.",
      label: "Ampliar retrato junto al mar",
      alt: "Retrato de Jonás de perfil junto al mar",
    },
    selfEyebrow: "03 / MI FORMA DE SER",
    selfTitle: "Cómo soy.",
    selfLead: "Curioso por naturaleza.",
    selfStory:
      "Me gusta conocer personas, entender cómo funcionan las cosas y aprender algo nuevo cada día. Antes era tímido; hoy me abro más, aunque sigo disfrutando mis ratos a solas.",
    traitsEyebrow: "Así me describen mis amigos",
    traits: ["Tranquilo", "Auténtico", "Amable", "Servicial"],
    faith: "Mi fe ocupa un lugar importante en mi vida y orienta muchas de mis decisiones.",
    selfScript: "Le doy demasiadas vueltas a algunas cosas. Estoy trabajando en eso.",
    selfNext: "LAS COSAS QUE DISFRUTO",

    enjoyEyebrow: "04 / LO QUE DISFRUTO",
    enjoyTitle: "Lo que disfruto.",
    enjoyLead: "Siempre hay algo por descubrir.",
    waterfallPhoto: {
      title: "Explorar",
      caption: "Montañas, ríos y tiempo al aire libre.",
      label: "Ampliar fotografía de la cascada",
      alt: "Una persona al pie de una gran cascada cubierta de vegetación",
    },
    photographyEyebrow: "FOTOGRAFÍA",
    photographyTitle: ["Mirar. Detenerme.", "Recordar."],
    photographyBody: "Fotografío para guardar paisajes, pequeños detalles y buenos momentos.",
    companyEyebrow: "EN BUENA COMPAÑÍA",
    companyTitle: "Y si es con amigos, mejor.",
    dayPhoto: {
      title: "Un día con amigos",
      caption: "Buenos momentos con mis amigos.",
      label: "Ampliar fotografía: Un día con amigos",
      alt: "Amigos con chalecos salvavidas junto a una moto acuática",
    },
    waterPhoto: {
      title: "Dentro del agua",
      caption: "Salir a descubrir, juntos.",
      label: "Ampliar fotografía: Dentro del agua",
      alt: "Dos personas con casco y chaleco dentro del agua, entre paredes de roca",
    },
    plansEyebrow: "EXPLORAR",
    plansTitle: "Mis planes favoritos.",
    plansBody: "Montañas, ríos, lugares nuevos y tiempo con amigos.",
    musicEyebrow: "MÚSICA",
    musicTitle: "La música que me acompaña.",
    musicBody: "Bandas sonoras, baladas de siempre y canciones con un poco de nostalgia.",
    storiesEyebrow: "HISTORIAS",
    storiesTitle: "Después de los créditos.",
    storiesBody: "Cine, anime y series para seguir pensando un rato más.",
    enjoyNext: "EXPERIENCIAS QUE ME HAN FORMADO",

    pathEyebrow: "05 / EXPERIENCIAS QUE ME HAN FORMADO",
    pathTitle: "Mi camino.",
    pathLead: "Servir. Aprender. Compartir.",
    preachingEyebrow: "PREDICAR · UNA CONSTANTE",
    preachingTitle: "Aprender a escuchar.",
    preachingBody: "Predicar desde joven me ayudó a conocer personas muy distintas y a dejar atrás parte de mi timidez.",
    preachingPhoto: {
      title: "Predicar, en compañía",
      caption: "Predicar · En compañía.",
      label: "Ampliar fotografía: Predicar, en compañía",
      alt: "Un grupo de distintas edades al aire libre durante la predicación",
    },
    littlePhoto: {
      title: "Desde pequeño",
      caption: "Un recuerdo de cuando era pequeño.",
      label: "Ampliar fotografía: Desde pequeño",
      alt: "Un adulto y tres niños compartiendo un momento de la etapa de predicación",
    },
    bethelEyebrow: "BETEL · UNA ETAPA ESPECIAL",
    bethelTitle: "Crecer junto a otros.",
    bethelBody:
      "En Betel, un centro de voluntarios de los testigos de Jehová, compartí trabajo, aprendizajes y amistades que siguen conmigo.",
    volunteerEyebrow: "RECUERDOS DEL VOLUNTARIADO DE MANTENIMIENTO",
    volunteerPhoto: {
      title: "Voluntariado de mantenimiento",
      caption: "Voluntariado de mantenimiento · Un momento compartido.",
      label: "Ampliar fotografía: Voluntariado de mantenimiento",
      alt: "Voluntarios de mantenimiento junto a un muro, varios con chalecos de trabajo",
    },
    workPhoto: {
      title: "En plena actividad",
      caption: "Voluntariado de mantenimiento · En plena actividad.",
      label: "Ampliar fotografía: En plena actividad",
      alt: "Tres voluntarios sobre una plataforma de trabajo",
    },
    pathNext: "Y TODAVÍA QUEDA CAMINO",

    dreamEyebrow: "06 / HACIA DONDE MIRO",
    dreamTitle: "Lo que sueño.",
    dreamBody:
      "Una vida sencilla, cerca de la naturaleza, con tiempo para la gente que quiero, trabajo que me entusiasme y lugares que todavía no conozco.",
    dreamScript: ["Todavía queda mucho", "por descubrir."],
    dreamPhoto: {
      title: "Lo que sueño",
      caption: "Una vida sencilla, cerca de la naturaleza.",
      label: "Ampliar fotografía junto al lago",
      alt: "Una persona de espaldas mirando un lago y las montañas",
    },

    endingEyebrow: "ESTO ES LO QUE LLEVO CONMIGO",
    endingTitle: ["Mi pequeño universo", "sigue creciendo."],
    endingBack: "VOLVER A LA CONSTELACIÓN ↑",
    endingOrbit: "VOLVER A ORBIT ↗",
    nextDestination: "Siguiente destino",
  },
  en: {
    heroEyebrow: "01 / ABOUT ME",
    heroHidden: "About me. ",
    heroTitle: "My little universe.",
    heroNote: ["Same person,", "different skies."],
    constellation: "Explore the six constellations",
    portraitAlt: "Jonás smiling in a coat, with lights behind him",
    place: "BONAO · DOMINICAN REPUBLIC",
    nodes: {
      roots: { title: "My roots", lead: "Where it all began.", alt: "A river surrounded by greenery in Bonao" },
      people: { title: "My people", lead: "The people who make a home.", alt: "Jonás with his family at an international convention" },
      self: { title: "Who I am", lead: "Still learning.", alt: "Jonás by the sea" },
      enjoy: { title: "What I enjoy", lead: "Curiosity, nature and good stories.", alt: "A large waterfall among greenery" },
      path: { title: "My path", lead: "Serving, learning and sharing.", alt: "A shared moment during maintenance volunteering" },
      dream: { title: "What I dream of", lead: "A simple life. So much to discover.", alt: "Someone gazing at a lake between mountains" },
    },
    invitation: "Choose a constellation",
    journeyNav: "Your place in the story",
    backToMap: "Back to the constellation",

    rootsEyebrow: "01 / WHERE IT STARTED",
    rootsTitle: "My roots.",
    rootsPlace: "Bonao · Dominican Republic",
    rootsCoordinates: "18°56′ N · 70°25′ W",
    rootsWords: "I grew up between rivers and mountains.",
    rootsStory:
      "Bonao is where I started. Growing up surrounded by mountains, rivers and so much green left something in me: I still look for places like that when I want to disconnect, think or simply take it all in. That’s where a lot of my love for exploring comes from.",
    rootsPhoto: {
      title: "My roots",
      caption: "Between rivers and mountains, with my friends.",
      label: "Enlarge photo of the waterfall with my friends",
      alt: "Jonás with his friends in front of a waterfall surrounded by greenery",
    },
    rootsNext: "AND THE PEOPLE BESIDE ME",

    peopleEyebrow: "02 / MY BONDS",
    peopleTitle: "My people.",
    peopleLead: "My family is my first home.",
    peopleSub: "My mother’s joy, my father’s hard work and my sister’s friendship.",
    familyPhoto: {
      title: "My family",
      caption: "Together at an international convention.",
      label: "Enlarge photo of my family",
      alt: "Jonás and his family in the auditorium of an international convention",
    },
    childhoodPhoto: {
      title: "Since we were kids",
      caption: "This is where we talked about our goals, like going to Bethel.",
      label: "Enlarge childhood memory with my best friend",
      alt: "Jonás and his best friend as kids, in front of rows of seats",
    },
    bethelPhoto: {
      title: "A shared dream",
      caption: "With my best friend during our time at Bethel.",
      label: "Enlarge photo of the two friends at Bethel",
      alt: "Jonás and his best friend at Bethel",
    },
    friendsLine: "My best friend and me, reaching goals and dreams together.",
    grandparentsPhoto: {
      title: "My grandparents",
      caption: "What I learned at their side.",
      label: "Enlarge photo of my maternal grandparents",
      alt: "Jonás’s maternal grandparents together at a table",
    },
    grandparentsEyebrow: "MY GRANDPARENTS",
    grandparentsLine: "Love, wisdom and so many memories.",
    chosenEyebrow: "FRIENDS WHO ARE ALMOST FAMILY",
    chosenTitle: "They make a home too.",
    friendsPhoto: {
      title: "Friends, almost family",
      caption: "Friends who feel like family.",
      label: "Enlarge photo: Friends, almost family",
      alt: "Friends spending time outdoors, among trees and garden chairs",
    },
    callsPhoto: {
      title: "Shared memories",
      caption: "Close, even through a screen.",
      label: "Enlarge photo: Shared memories",
      alt: "Collage of video calls with friends, framed with leaves and messages",
    },
    peopleNext: "A LITTLE MORE ABOUT ME",

    selfPhoto: {
      title: "By the sea",
      caption: "A moment outdoors.",
      label: "Enlarge portrait by the sea",
      alt: "Profile portrait of Jonás by the sea",
    },
    selfEyebrow: "03 / WHO I AM",
    selfTitle: "Who I am.",
    selfLead: "Curious by nature.",
    selfStory:
      "I like meeting people, understanding how things work and learning something new every day. I used to be shy; these days I open up more, though I still enjoy my time alone.",
    traitsEyebrow: "How my friends describe me",
    traits: ["Calm", "Genuine", "Kind", "Helpful"],
    faith: "My faith holds an important place in my life and guides many of my decisions.",
    selfScript: "I overthink some things. I’m working on it.",
    selfNext: "THE THINGS I ENJOY",

    enjoyEyebrow: "04 / WHAT I ENJOY",
    enjoyTitle: "What I enjoy.",
    enjoyLead: "There’s always something to discover.",
    waterfallPhoto: {
      title: "Exploring",
      caption: "Mountains, rivers and time outdoors.",
      label: "Enlarge photo of the waterfall",
      alt: "A person at the foot of a large waterfall covered in greenery",
    },
    photographyEyebrow: "PHOTOGRAPHY",
    photographyTitle: ["Look. Pause.", "Remember."],
    photographyBody: "I take photos to hold on to landscapes, small details and good moments.",
    companyEyebrow: "IN GOOD COMPANY",
    companyTitle: "Even better with friends.",
    dayPhoto: {
      title: "A day with friends",
      caption: "Good times with my friends.",
      label: "Enlarge photo: A day with friends",
      alt: "Friends in life jackets next to a jet ski",
    },
    waterPhoto: {
      title: "In the water",
      caption: "Heading out to discover, together.",
      label: "Enlarge photo: In the water",
      alt: "Two people in helmets and life jackets in the water, between rock walls",
    },
    plansEyebrow: "EXPLORE",
    plansTitle: "My favorite plans.",
    plansBody: "Mountains, rivers, new places and time with friends.",
    musicEyebrow: "MUSIC",
    musicTitle: "The music that keeps me company.",
    musicBody: "Film scores, timeless ballads and songs with a touch of nostalgia.",
    storiesEyebrow: "STORIES",
    storiesTitle: "After the credits.",
    storiesBody: "Films, anime and series that keep me thinking a little longer.",
    enjoyNext: "EXPERIENCES THAT SHAPED ME",

    pathEyebrow: "05 / EXPERIENCES THAT SHAPED ME",
    pathTitle: "My path.",
    pathLead: "Serve. Learn. Share.",
    preachingEyebrow: "PREACHING · A CONSTANT",
    preachingTitle: "Learning to listen.",
    preachingBody: "Preaching from a young age helped me meet very different people and leave some of my shyness behind.",
    preachingPhoto: {
      title: "Preaching, together",
      caption: "Preaching · Together.",
      label: "Enlarge photo: Preaching, together",
      alt: "A group of people of different ages outdoors during the preaching work",
    },
    littlePhoto: {
      title: "Since I was little",
      caption: "A memory from when I was little.",
      label: "Enlarge photo: Since I was little",
      alt: "An adult and three children sharing a moment during the preaching work",
    },
    bethelEyebrow: "BETHEL · A SPECIAL CHAPTER",
    bethelTitle: "Growing alongside others.",
    bethelBody:
      "At Bethel, a volunteer center of Jehovah’s Witnesses, I shared work, lessons and friendships that are still with me.",
    volunteerEyebrow: "MEMORIES FROM MAINTENANCE VOLUNTEERING",
    volunteerPhoto: {
      title: "Maintenance volunteering",
      caption: "Maintenance volunteering · A shared moment.",
      label: "Enlarge photo: Maintenance volunteering",
      alt: "Maintenance volunteers next to a wall, several in work vests",
    },
    workPhoto: {
      title: "Hard at work",
      caption: "Maintenance volunteering · Hard at work.",
      label: "Enlarge photo: Hard at work",
      alt: "Three volunteers on a work platform",
    },
    pathNext: "AND THERE’S STILL A WAY TO GO",

    dreamEyebrow: "06 / WHERE I’M HEADED",
    dreamTitle: "What I dream of.",
    dreamBody:
      "A simple life, close to nature, with time for the people I love, work that excites me and places I’ve yet to see.",
    dreamScript: ["There’s still so much", "left to discover."],
    dreamPhoto: {
      title: "What I dream of",
      caption: "A simple life, close to nature.",
      label: "Enlarge photo by the lake",
      alt: "A person seen from behind looking out at a lake and the mountains",
    },

    endingEyebrow: "THIS IS WHAT I CARRY WITH ME",
    endingTitle: ["My little universe", "keeps growing."],
    endingBack: "BACK TO THE CONSTELLATION ↑",
    endingOrbit: "BACK TO ORBIT ↗",
    nextDestination: "Next destination",
  },
});
